### ISSUE TITLE
Power Ai authentication fails

### ISSUE THREAD

**Issue by KumailHussain** [IBM/powerai-vision-object-detection#23]
Every time i login into this [https://ny1.ptopenlab.com/AIVision/index.html]()
redirects to login but login never happens getting error message
**Authentication Failed! Please Retry**
Even i tried resetting password

**Comment by markstur** [comment]
FYI, I was able to login just now.  Had to accept warnings and there was some redirect, but no loop.  So at least for my ID it is working.

**Comment by KumailHussain** [comment]
@markstur ID is not activating i got the activation link in my email but got the message activation failed every time, I dont know why?

**Comment by BuiTanDai** [comment]
Have trouble same as KumailHussain. "User active failed"

**Comment by stevemart** [comment]
@KumailHussain @BuiTanDai I am raising this issue to the team that supports supervessel. Can you provide me with the emails you are using to register?

**Comment by KumailHussain** [comment]
kumi.leo1@gmail.com
This is my email

**Comment by BuiTanDai** [comment]
Of course, 14520119@gm.uit.edu.vn

**Comment by KumailHussain** [comment]
@stevemart any updates??

**Comment by markstur** [comment]
@KumailHussain @BuiTanDai is this still an issue.  You probably need to re-register, but you should be able to.

**Comment by markstur** [comment]
I'm going to close this as I really hope it was resolved via e-mails (specific to these users) a long time ago and also I think the whole re-register thing happened after this issue.  Please let us know if there is still an issue.

**Comment by swapnilmarathe007** [comment]
Not able to connect to supervessl site too.
giving same error authentication failed and while register its time out
help me to fix this issue

**Comment by amardeepjaiman** [comment]
https://ny1.ptopenlab.com/AIVision/index.html not able to use this link. Some error occurd message is shown.

**Comment by markstur** [comment]
There is a new trial registration open here: https://developer.ibm.com/linuxonpower/deep-learning-powerai/vision/access-registration-form/

Sorry about the inconvenience.
