### ISSUE TITLE
Uncaught SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by supppppLT** [IBM/powerai-vision-object-detection#33]
I followed the steps in the readme file and got this error whenever I run the application. 

Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (index.js:212)

Any advice? Thank you in advance!

**Comment by stevemart** [comment]
@markstur take a look at this when you're back

**Comment by markstur** [comment]
Closing as cannot reproduce.  Wonder if this was a temporary error w/ a not-ready state that is fixed on retry.  Could use more info.
