### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by psyntium** [IBM/powerai-vision-object-detection#53]
I was trying to do auto_detect on a video from the URL given in the deployed model page. The url looks like this:

> https://ny1.ptopenlab.com/powerai-vision-ny/demo-video?webapi_id=<API_ID>#/

After uploading the mp4 video successfully, I clicked detect button and no result comes up. When checking the network from debug view, I'm getting CSRF issue:

> Referer checking failed - https://ny1.ptopenlab.com/powerai-vision-ny?webapi_id=<API_ID>#/
>  does not match any trusted origins.

**Comment by markstur** [comment]
I also get a Forbidden doing that on ny1.ptopenlab.com.  It is not really part of this code pattern. You should be able to test your model w/ image files and use the nodejs app, too.  For enabling the video feature, can you try to request help from the trial host?  My signup e-mail suggests here:

Feel free to reach us for help at  https://developer.ibm.com/answers/smart-spaces/361/powerai.html

**Comment by psyntium** [comment]
Thanks for the suggestion.. will try to post on dwanswer as well

**Comment by markstur** [comment]
Not sure if we got an answer, but don't think this is an ongoing issue w/ the code pattern. Closing.
